ecc-cms/config/routes.rb
Rails.application.routes.draw do


  get '/search' => 'search#search', :as => :search
  get 'admin' => 'admin#index'
  get 'users/:id/delete' => 'users#destroy', :as => :delete_user
  get '/browse' => 'documents#browse', :as => :browse_documents

  #Start single document routs
  get 'ecodes/:org/:id' => 'documents#show', :as => :show_document
  get 'ecodes/:org/:id/edit'=> 'documents#edit', :as => :edit_document
  patch 'ecodes/:org/:id' => 'documents#update'
  get '/documents/new', to: 'documents#new'
  post '/documents', to: 'documents#create'
  get 'ecodes/:org/:id/delete' => 'documents#destroy', :as => :delete_document
  #End single Document Routes
  resources :documents
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'logout' => 'sessions#destroy'
  resources :users

  #Start Static Page Routes
  get '/' => 'static#home'
  get '/about' => 'static#about'
  get '/whycodes' => 'static#whycodes'
  get '/collectionpolicy' => 'static#collectionpolicy'
  get '/contact' => 'static#contact'
  get '/authoringcode' => 'static#authoringcode'
  get '/learn' => 'static#learn'
  get '/engage' => 'static#engage'
  get '/userguide' => 'static#userguide'
  #End Static Page Routes
end

ecc-cms/app/models/document.rb
require 'elasticsearch/persistence/model'

class Document
  # Use ES Presistance
  include Elasticsearch::Persistence::Model

  # Name the Index over here
  index_name 'document'

  # Define the indexing over here - OPTIMIZE THIS!
  analyzed_and_raw = { fields: {
    name: { type: 'text', analyzer: 'snowball' },
    raw:  { type: 'keyword' }
  } }

  # Define all attributes and mapping types over here
  attribute :title, String, mapping: analyzed_and_raw
  attribute :year, String, mapping: analyzed_and_raw
  attribute :institution, String, mapping: analyzed_and_raw
  attribute :contributor, String, mapping: analyzed_and_raw
  attribute :code_versions, String, default: [], mapping: analyzed_and_raw
  attribute :date_publish, Date
  attribute :ecc_date, Date
  attribute :author_site, String, mapping: analyzed_and_raw
  attribute :orig_url, String, mapping: analyzed_and_raw
  attribute :description, String, mapping: analyzed_and_raw
  attribute :notes, String, mapping: analyzed_and_raw
  attribute :doi, String, mapping: analyzed_and_raw
  attribute :copyright, String, mapping: analyzed_and_raw
  attribute :topics, String, mapping: analyzed_and_raw
  attribute :fields, String, mapping: analyzed_and_raw
  attribute :backup_url, String, mapping: analyzed_and_raw
  
  # Validations over here
  # validates :name, presence: true
  # Internal Methods over here
  # def document
  #   Document.search(
  #     { query: {
  #         has_parent: {
  #           type: 'document',
  #           query: {
  #             bool: {
  #               filter: {
  #                 ids: { values: [ self.id ] }
  #               }
  #             }
  #           }
  #         }
  #       },
  #       size: 100
  #     },
  #     { type: 'document' }
  # )
  # end



end

ecc-cms/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:show, :browse]
  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end
  
  def browse
    all_docs=Document.all
    @documents =  Kaminari.paginate_array(all_docs).page(params[:page]).per(5)
    
  end

  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  def new
    @document =Document.new
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :year, :institution, :contributor, :code_versions, :date_publish, :ecc_date, :author_site, :orig_url, :description, :notes, :doi, :copyright, :topics, :fields, :backup_url)
    end
end

ecc-cms/app/helpers/documents_helper.rb
module DocumentsHelper
end

ecc-cms/app/views/documents/_form.html.erb
<script>
$(document).ready(function() {
$('.datepicker').pickadate({   
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 1000, // Creates a dropdown of 10 years to control year
	    min: [1850,1,1],
	    max: true,
            format: 'dd-mm-yyyy',
            closeOnSelect: true,
            closeOnClear: true
        });
    $('select').material_select();
  });
</script>

<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :year, 'Year Published' %>
    <%= f.text_area :year %>
  </div>

  <div class="field">
    <%= f.label :institution, 'Organization' %>
    <%= f.text_field :institution %>
  </div>

  <div class="field">
    <%= f.label :contributor%>
    <%= f.text_field :contributor %>
  </div>

  <div class="field">
    <%= f.label :code_versions %>
    <%= f.text_field :code_versions %>
  </div>

  <div>
    <%= f.label :date_publish, 'Date Published' %>
    <%= f.text_field :date_publish, :class=> "datepicker"%>
  </div>

  <div>
    <%= f.label :ecc_date,'ECC Date' %>
    <%= f.text_field :ecc_date, :class=> "datepicker"%>
  </div>

  <div class="field">
    <%= f.label :author_site,'Organization URL' %>
    <%= f.text_field :author_site %>
  </div>

  <div class="field">
    <%= f.label :orig_url, 'Origional URL' %>
    <%= f.text_field :orig_url %>
  </div>

  <div class="field">
    <%= f.label :description, 'Full Text' %>
    <%= f.trix_editor :description %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :doi, 'DOI' %>
    <%= f.text_field :doi %>
  </div>

  <div class="field">
    <%= f.label :copyright,'Copyright' %>
    <%= f.text_area :copyright %>
  </div>

  <div class="field">
    <%= f.label :topics %>
    <%= f.text_area :topics %>
  </div>

  <div class="field">
    <%= f.label :fields %>
    <%= f.text_area :fields %>
  </div>

  <div class="field">
    <%= f.label :backup_url, 'Backup URL' %>
    <%= f.text_field :backup_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ecc-cms/app/views/documents/brouse.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Codes</h1>
  <% @documents.each do |document| %>
  <div class="row">
    <div class="col s12 m12">
      <div class="card medium hoverable">
	<div class="card-content">
          <span class="card-title"><%= document.title %></span>
	  <div class="divider"></div>
	  <%= document.institution %>
	  <div class="truncated">
	  <%= document.description.html_safe %>
	  </div>
	</div>
	<div class="card-action">
              <%= link_to 'Show',document, class: 'white-text red lighten-1 btn' %>
	</div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

ecc-cms/app/views/documents/browse.html.erb
<div class="container">
  <h2>Codes</h2>
    <% @documents.each do |document| %>
      <div class="row">
        <div class="col s12 m12">
          <div class="card medium hoverable">
            <div class="card-content">
              <span class="card-title"><%= document.title %></span>
              <div class="divider"></div>
              <%= document.institution %>
                <div class="truncated">
                  <%= document.description.html_safe %>
                </div>
            </div>
            <div class="card-action">
              <%= link_to 'Show',document, class: 'white-text red accent-4 btn' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="center-align">
        <%=paginate @documents, window: 2%>
      </div>
</div>
</div>

<% if notice %>
  <script>
    var message = <%= ("'" + notice.to_s + "'").html_safe %>
      Materialize.toast(message, 3000);
  </script>
  <% end %>

ecc-cms/app/views/documents/edit.html.erb
<div class='container'>
  <h2>Editing Document</h2>
  <%= link_to 'Back', documents_path, class: 'white-text red accent-4 btn' %>
    <br><br>

    <%= render 'form', document: @document %>
      <br>
      <%= link_to 'Show', @document, class: 'white-text red accent-4 btn' %>
        <%= link_to 'Back', documents_path, class: 'white-text red accent-4 btn' %>
          <br><br>
</div>

ecc-cms/app/views/documents/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="container">
  <h1>Documents</h1>

  <%= link_to 'New Document', new_document_path, class: "white-text red accent-4 btn" %>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td>
              <%= document.title %>
            </td>
            <td>
              <%= link_to 'Show', document, class: "white-text red accent-4 btn" %>
            </td>
            <td>
              <%= link_to 'Edit', edit_document_path(:org => document.institution, :id => document.id), class: "white-text red accent-4 btn" %>
            </td>
            <td>
              <%= link_to 'Destroy', delete_document_path(:org => document.institution, :id => document.id), class: "white-text red accent-4 btn" %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>

    <br>
    <%= link_to 'New Document', new_document_path, class: "white-text red accent-4 btn" %>

      <br><br><br>

</div>

ecc-cms/app/views/documents/new.html.erb
<div class="container">
  <h2>New Document</h2>

  <%= render 'form', document: @document %>
    <br>

    <%= link_to 'Back', documents_path, class: 'white-text red accent-4 btn' %>
      <br><br>
</div>

ecc-cms/app/views/documents/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-content">
      <span class="card-title"><%= @document.title %></span>
      <div class="section">
        <div>
          <span style="font-weight: 600">Institution: </span><span><%= @document.institution %></span>
        </div>
        <div>
          <span style="font-weight: 600">Date Published: </span><span><%= @document.date_publish.to_s %></span>
        </div>
        <div>
          <span style="font-weight: 600">Contributor: </span><span><%= @document.contributor.length != 0? @document.contributor : "None" %></span>
        </div>
        <div>
          <span style="font-weight: 600">Code Versions: </span><span><%= @document.code_versions.length != 0? @document.code_versions : "None" %></span>
        </div>
        <div>
          <span style="font-weight: 600">Date Added to ECC: </span><span><%= @document.ecc_date %></span>
        </div>
        <div>
          <span style="font-weight: 600">Author Site: </span><span><%= @document.author_site.length != 0?@document.author_site : "None" %></span>
        </div>
        <div>
          <span style="font-weight: 600">Original URL: </span>
          <span>
                        <% if @document.orig_url.length != 0 %>
                            <a href="<%= @document.orig_url %>">
                                <%= @document.orig_url %>
                            </a>
                        <% else %>
                            <%= "None" %>
                        <% end %>
                    </span>
        </div>
        <div>
          <span style="font-weight: 600">DOI: </span><span><%= @document.doi.length != 0?@document.doi : "None" %></span>
        </div>
      </div>

      <div class="section">
        <p style="font-weight: 600">Text</p>
        <%= @document.description.html_safe %>
      </div>
      <div class="section">
        <p style="font-weight: 600">Notes</p>
        <p>
          <%= @document.notes.length != 0? @document.notes : "None" %>
        </p>
      </div>
      <div class="section">
        <p style="font-weight: 600">Copyright</p>
        <p>
          <%= @document.copyright %>
        </p>
      </div>
      <div class="section">
        <div>
          <p style="font-weight: 600">Topics</p>
          <% @document.topics.split(',').each do |t| %>
            <div class='chip'>
              <%= t %>
            </div>
            <% end %>
        </div>
        <div>
          <p style="font-weight: 600">Fields</p>
          <% @document.fields.split(',').each do |f| %>
            <div class='chip'>
              <%= f %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
    <div class="card-action">
      <% if session[:user_id] %>
        <%= link_to 'Back', documents_path, :class => 'white-text red accent-4 btn'%>
          <%= link_to 'Edit', edit_document_path(@document), :class => 'white-text red accent-4 btn'%>
            <% else %>
              <%= link_to 'Back', browse_documents_path, :class => 'white-text red accent-4 btn' %>
                <% end %>
    </div>
  </div>
</div>

<% if notice %>
  <script>
    var message = <%= ("'" + notice.to_s + "'").html_safe %>
      Materialize.toast(message, 3000);
  </script>
  <% end %>