ecc-cms/config/routes.rb
Rails.application.routes.draw do


  get '/search' => 'search#search', :as => :search
  get 'admin' => 'admin#index'
  get 'users/:id/delete' => 'users#destroy', :as => :delete_user
  get '/browse' => 'documents#browse', :as => :browse_documents

  #Start single document routs
  get 'ecodes/:org/:id' => 'documents#show', :as => :show_document
  get 'ecodes/:org/:id/edit'=> 'documents#edit', :as => :edit_document
  patch 'ecodes/:org/:id' => 'documents#update'
  get '/documents/new', to: 'documents#new'
  post '/documents', to: 'documents#create'
  get 'ecodes/:org/:id/delete' => 'documents#destroy', :as => :delete_document
  #End single Document Routes
  resources :documents
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get 'logout' => 'sessions#destroy'
  resources :users

  #Start Static Page Routes
  get '/' => 'static#home'
  get '/about' => 'static#about'
  get '/whycodes' => 'static#whycodes'
  get '/collectionpolicy' => 'static#collectionpolicy'
  get '/contact' => 'static#contact'
  get '/authoringcode' => 'static#authoringcode'
  get '/learn' => 'static#learn'
  get '/engage' => 'static#engage'
  get '/userguide' => 'static#userguide'
  #End Static Page Routes
end

ecc-cms/app/models/user.rb
require 'elasticsearch/persistence/model'

class User
    # Use ES Presistance
    include Elasticsearch::Persistence::Model
    include ActiveModel::SecurePassword
    has_secure_password(validations: false)

    # Name the Index over here
    index_name 'user'
    
    # attributes
    attribute :name, String, mapping: {index: "not_analyzed"}
    attribute :password_digest, String, mapping: {index: "not_analyzed"}

    def self.find_by_name(name)
    users = User.search(query:{match:{name: name}})
    return nil if users.blank?
    return nil if users.count > 1
    return users.first
    rescue => ex
      return nil
  end

end

ecc-cms/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_url, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    @user = User.all
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

ecc-cms/app/helpers/users_helper.rb
module UsersHelper
end

ecc-cms/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <legend>Enter User Details</legend>
    
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

ecc-cms/app/views/users/edit.html.erb
<div class="container">
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<br>
<%= link_to 'Show', @user, class: 'white-text red accent-4 btn'  %>
<%= link_to 'Back', users_path, class: 'white-text red accent-4 btn'  %>
<br><br>
</div>

ecc-cms/app/views/users/index.html.erb
<div class="container">
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: 'white-text red accent-4 btn'  %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'white-text red accent-4 btn'  %></td>
	<td><%= link_to 'Destroy', delete_user_path(user,:id => user.id), class: 'white-text red accent-4 btn'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'white-text red accent-4 btn'  %>
<br><br>
<% if notice %>
    <script>
        var message = <%= ("'" + notice.to_s + "'").html_safe %>
        Materialize.toast(message, 3000);
    </script>
<% end %>
</div>

ecc-cms/app/views/users/new.html.erb
<div class='container'>
<h1>New User</h1>

<%= render 'form', user: @user %>
<br>
<%= link_to 'Back', users_path, class: 'white-text red accent-4 btn'  %>
<br><br>
</div>

ecc-cms/app/views/users/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<br>
<%= link_to 'Edit', edit_user_path(@user), class: 'white-text red accent-4 btn'  %>
<%= link_to 'Back', users_path, class: 'white-text red accent-4 btn'  %>
<br><br>
</div>